### ISSUE TITLE
导航改进

### ISSUE THREAD

**Issue by re-ovo** [Nthily/Chatty#12]
一个建议，这个库可以用注解定义导航，基于ksp，更优雅 😋

https://github.com/raamcosta/compose-destinations

**Comment by Nthily** [comment]
感谢建议，这个项目是一本书的实战项目，目前还在用官方的 Navigation。
后续有机会试试这个库 ！👍

**Comment by re-ovo** [comment]
其实这就是官方的Navigation, 只是支持了使用注解定义 😋
